-- MySQL Script generated by MySQL Workbench
-- Sun Feb 23 19:40:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Voos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Voos` (
  `idVoos` INT NOT NULL,
  `saida` DATETIME NULL,
  `chegada` DATETIME NULL,
  `escala` VARCHAR(60) NULL,
  PRIMARY KEY (`idVoos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aeroporto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aeroporto` (
  `idAeroporto` INT NULL,
  `Aeroporto` VARCHAR(70) NULL,
  `NomeUsual` VARCHAR(45) NULL,
  `NomeOficial` VARCHAR(45) NULL,
  `CodigoICAO` VARCHAR(6) NULL,
  `CodigoIATA` VARCHAR(6) NULL,
  `Localizacao` VARCHAR(60) NULL,
  `Administracao` VARCHAR(40) NULL,
  `Voos_idVoos` INT NOT NULL,
  PRIMARY KEY (`idAeroporto`),
  INDEX `fk_Aeroporto_Voos_idx` (`Voos_idVoos` ASC) VISIBLE,
  CONSTRAINT `fk_Aeroporto_Voos`
    FOREIGN KEY (`Voos_idVoos`)
    REFERENCES `mydb`.`Voos` (`idVoos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aeronaves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aeronaves` (
  `idAeronaves` INT NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Proprietario` VARCHAR(60) NULL,
  `CPF_CNPJ` INT NULL,
  `NM_Operador` VARCHAR(45) NULL,
  `UF_Operador` VARCHAR(45) NULL,
  `NR_Cert_Matricula` INT NULL,
  `NR_Serie` INT NULL,
  `CD_Categoria` VARCHAR(45) NULL,
  `DS_Modelo` VARCHAR(45) NULL,
  `NM_Fabricante` VARCHAR(45) NULL,
  `CD_Tipo_Icao` VARCHAR(45) NULL,
  `NR_Tripulacao` INT NULL,
  `NR_Passageiros` INT NULL,
  `NR_Assentos` INT NULL,
  `NR_Ano_Fabricacao` DATE NULL,
  PRIMARY KEY (`idAeronaves`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Voos_has_Aeronaves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Voos_has_Aeronaves` (
  `Voos_idVoos` INT NOT NULL,
  `Aeronaves_idAeronaves` INT NOT NULL,
  PRIMARY KEY (`Voos_idVoos`, `Aeronaves_idAeronaves`),
  INDEX `fk_Voos_has_Aeronaves_Aeronaves1_idx` (`Aeronaves_idAeronaves` ASC) VISIBLE,
  INDEX `fk_Voos_has_Aeronaves_Voos1_idx` (`Voos_idVoos` ASC) VISIBLE,
  CONSTRAINT `fk_Voos_has_Aeronaves_Voos1`
    FOREIGN KEY (`Voos_idVoos`)
    REFERENCES `mydb`.`Voos` (`idVoos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voos_has_Aeronaves_Aeronaves1`
    FOREIGN KEY (`Aeronaves_idAeronaves`)
    REFERENCES `mydb`.`Aeronaves` (`idAeronaves`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
