create table Aeroporto (
Id_Aeroporto int PRIMARY KEY NOT NULL,
Aeroporto CHAR(70) NOT NUll ,
NomeUsual CHAR(50),
NomeOficial TEXT,
CodigoICAO CHAR(6) ,
CodigoIATA CHAR(6)  ,
Localizacao CHAR(60)  ,
Administracao CHAR(40) 
);

INSERT INTO Aeroporto(Id_Aeroporto,Aeroporto,NomeUsual,NomeOficial,CodigoICAO,CodigoIATA,Localizacao,Administracao)
VALUES	(1,'Amapá','Amapá','Aeroporto de Amapá','SBAM','null','Amapá/AP','Municipal'),
 		(2,'Apuí','Apuí','Aeroporto de Apuí','SWYN','null','Apuí/AM','Municipal'),
 		(3,'Arapiraca','Arapiraca','Aeroporto de Arapiraca','SNAL','APQ','Arapiraca/AL','Municipal'),
 		(4,'Barcelos','Barcelos','Aeroporto de Barcelos','SWBC','BAZ','Barcelos/AM','Municipal'),
 		(5,'Barreirinha','Barreirinha','Aeroporto de Barreirinha','SWBI','null','Barreirinha/AM','Municipal'),
 		(6,'Belém','Val-de-Cães','Aeroporto Internacional de Belém Val-de-Cães','SBBE','BEL','Belém/PA','Infraero'),
		(7,'Belo Horizonte','Confins','Aeroporto Internacional de Belo Horizonte-Confins','SBCF','CNF','Confins/MG','BHAirport'),
		(8,'Belo Horizonte','Pampulha','Aeroporto Carlos Drummond de Andrade','SBBH','PLU','BeloHorizonte/MG','Infraero'),
		(9,'Borba','Borba','Aeroporto de Borba','SWBR','null','Borba/AM','Municipal'),
		(10,'Brasileia','Brasileia','Aeroporto de Brasileia','SWBS','null','Brasileia/AC','Municipal'),
		(11,'Brasília Internacional','Brasília','Aeroporto Internacional de Brasília','SBBR','BSB','LagoSul/DF','Inframérica'),
 		(12,'Calçoene','Calçoene','Aeroporto de Calçoene','SNCC','null','Calçoene/AP','Municipal'),				(13,'Campinas','Viracopos','AeroportoInternacional de Viracopos/Campinas','SBKP','VCP','Campinas/SP','Aeroportos Brasil Viracopos'),
 		(14,'Campo dos Amarais','Amarais','Aeroporto Campo dos Amarais','SDAM','CPQ','Campinas/SP','Voa-SP'),
		(15,'Campo de Marte','Campode Marte','AeroportoCampodeMarte','SBMT','null','SãoPaulo/SP','Infraero'),
		(16,'Caruaru','Caruaru','Aeroporto de Caruaru','SNRU','CAU','Caruaru/PE','Municipal'),
		(17,'Carauari','Carauari','Aeroporto de Carauari','SWCA','CAF','Caraurari/AM','Municipal'),
		(18,'Cascavel','Cascavel','Aeroporto de Cascavel','SBCA','CAC','Cascavel/PR','Municipal'),
		(19,'Cascavel','Aeroleve','Aeroleve','SILQ','null','Cascavel/PR','Privado'),
		(20,'Coari','Coari','Aeroporto Regional de Coari','SWKO','CIZ','Coari/AM','Municipal'),
		(21,'Conceição do Araguaia','Conceição do Araguaia','Aeroporto de Conceição do Araguaia','SBAA','CDJ','Conceição do Araguaia/PA','Municipal'),
		(22,'Cruzeiro do Sul','Cruzeiro do Sul','Aeroporto Internacional de Cruzeiro do Sul','SBCZ','CZS','Cruzeiro do Sul/AC','Infraero'),
		(23,'Curitiba','Bacacheri','Aeroporto do Bacacheri','SBBI','BFH','Curitiba/PR','Infraero'),
		(24,'Curitiba Internacional','Curitiba','Aeroporto Internacional Afonso Pena','SBCT','CWB','SãoJosédosPinhais/PR','Infraero'),
		(25,'Feijó','Feijó','Aeroporto de Feijó','SWFJ','FEJ','Feijó/AC','Municipal'),
		(26,'Flores','Flores','Aeroporto de Flores','SWFN','null','Manaus/AM','Municipal'),
		(27,'Florianópolis','Florianópolis','Aeroporto Internacional Hercílio Luz','SBFL','FLN','Florianópilis/SC','FloripaAirport'),
		(28,'Fortaleza','Pinto Martins','Aeroporto Internacional Pinto Martins','SBFZ','FOR','Fortaleza/CE','Infraero'),
		(29,'Foz do Iguaçú','Foz do Iguaçú','Aeroporto Internacional Cataratas','SBFI','IGU','FozdoIguaçú/PR','Infraero'),
		(30,'Goianá','Goianá','Aeroporto Presidente Itamar Franco','SBZM','IZA','Goianá/MG','Infraero'),
		(31,'Goiânia','Goiânia','Aeroporto Internacional Santa Genoveva','SBGO','GYN','Goiânia/GO','Infraero'),
		(32,'Guarulhos','Cumbica','AeroportoInternacionaldeSãoPaulo-Guarulhos','SBGR','GRU','Guarulhos/SP','GRUAirport'),
		(33,'Imperatriz','Imperatriz','Aeroporto de Imperatriz','SBIZ','IMP','Imperatriz/MA','Infraero'),
		(34,'Jericoacoara','Jericoacoara','Aeroporto Regional Comandante Ariston Pessoa','SBJE','JJD','Cruz/CE','Infraero'),
		(35,'Joinville','Cubatão','Aeroporto de Joinville','SBJV','JOI','Joinville/SC','Infraero'),
		(36,'João Pessoa','Castro Pinto','Aeroporto Internacional de João Pessoa-Bayeux','SBJP','JPA','Bayeux/PB','Infraero'),
		(37,'Juiz de Fora','Juiz de Fora','Aeroporto de Juiz de Fora','SBJF','JDF','JuizdeFora/MG','Municipal'),
		(38,'Jundiaí','Jundiaí','Aeroporto de Jundiaí','SBJD','QDV','Jundiaí/SP','Daesp'),
		(39,'Macapá','Macapá','Aeroporto Internacional de Macapá-Alberto Alcolumbre','SBMQ','MCP','Macapá/AP','Infraero'),
		(40,'ManausInternacional','Manaus','Aeroporto Internacional de Manaus','SBEG','MAO','Manaus/AM','Infraero'),
		(41,'ManducaLeão','ManducaLeão','Aeroporto Manduca Leão','SNML','null','RioLargo/AL','Municipal'),
		(42,'Maceió','Maceió','Aeroporto Internacional Zumbi dos Palmares','SBMO','MCZ','RioLargo/AL','Infraero'),
		(43,'Mossoró','Mossoró','Aeroporto Governador Dix-SeptRosado','SBMS','MVF','Mossoró/RN','Estadual'),
		(44,'Navegantes','Navegantes','Aeroporto Internacional de Navegantes','SBNF','NVT','Navegantes/SC','Infraero'),
		(45,'Natal','Natal','Aeroporto Internacional de Natal','SBSG','NAT','São Gonçalo do Amarante/RN','Inframérica'),
		(46,'NovoCampo','NovoCampo','AeroportoNovoCampo','SWNK','null','BocadoAcre/AM','Municipal'),
		(47,'Oiapoque','Oiapoque','Aeroporto de Oiapoque','SBOI','null','Oiapoque/AP','Municipal'),
		(48,'Paço do Lumiar','Paço do Lumiar','Aeroporto de Paçodo Lumiar','SNOZ','null','Paço do Lumiar/MA','Municipal'),
		(49,'PalmeirasdoJavari','PalmeirasdoJavari','AeroportoPalmeirasdoJavari','SWJV','null','Atalaia do Norte/AM','Municipal'),
		(50,'Parnaíba','Parnaíba','Aeroporto Internacional Prefeito Doutor João Silva Filho','SBPB','PHB','Parnaíba/PI','Infraero'),
		(51,'Penedo','Penedo','Aeroporto de Penedo','SNPE','null','Penedo/AL','Municipal'),
		(52,'Ponta Grossa','Sant ana','Comandante Antonio Amilton Beraldo','SSZW','PGZ','Ponta Grossa/PR','Municipal'),
		(53,'Porto Alegre','Porto Alegre','Aeroporto Internacional Salgado Filho','SBPA','POA','PortoA legre/RS','Fraport'),
		(54,'Porto Grande','Porto Grande','Aeroporto de Porto Grande','SNPG','null','PortoGrande/AP','Municipal'),
		(55,'Recife','Guararapes','Aeroporto Internacional do Recife','SBRF','REC','Recife/PE','Aena Internacional'),
		(56,'Ribeirão Preto','Ribeirão Preto','Aeroporto de Ribeirão Preto','SBRP','RAO','Ribeirão Preto/SP','Daesp'),
		(57,'Rio Branco','Rio Branco','Aeroporto Internacional de Rio Branco','SBRB','RBR','Rio Branco/AC','Infraero'),
		(58,'Rio de Janeiro','Santos Dumont','Aeroporto Santos Dumont','SBRJ','SDU','Rio de Janeiro/RJ','Infraero'),
		(59,'Rio de Janeiro','Galeão','Aeroporto Internacional do Rio de Janeiro-Galeão','SBGL','GIG','RiodeJaneiro/RJ','RIOgaleão'),
		(60,'Rio de Janeiro','Jacarepaguá','Aeroporto de Jacarepaguá','SBJR','null','Rio de Janeiro/RJ','Infraero'),
		(61,'Rondonópolis','Rondonópolis','Aeroporto Municipal Maestro Marinho Franco','SBRD','ROO','Rondonópolis/MT','Emconcessão[4]'),
		(62,'Santa Maria','Santa Maria','Aeroporto de Santa Maria','SBSM','RIA','Santa Maria/RS','Municipal'),
		(63,'Santa Rosa do Purus','Santa Rosa do Purus','Aeroporto de Santa Rosa do Purus','SDOE','null','SantaRosadoPurus/AC','Municipal'),
		(64,'Santos','Base Aérea de Santos','Base Aérea de Santos','SBST','SSZ','Guarujá/SP','Força Aérea Brasileira'),
		(65,'São Carlos','Latam','Aeroporto Internacional de São Carlos','SDSC','QSC','São Carlos/SP','Daesp'),
		(66,'São Luís','São Luís','Aeroporto Internacional de São Luís','SBSL','SLZ','São Luís/MA','Infraero'),
		(67,'São Paulo','Congonhas','Aeroporto de Congonhas','SBSP','CGH','São Paulo/SP','Infraero'),
		(68,'Sena Madureira','Sena Madureira','Aeroporto de Sena Madureira','SWSN','ZMD','Sena Madureira/AC','Municipal'),
		(69,'Sorocaba','Sorocaba','Aeroporto de Sorocaba','SDCO','SOD','Sorocaba/SP','Daesp'),
		(70,'Surumu','Surumu','Aeroporto de Surumu','SWMU','null','Pacaraima/RR','Municipal'),
		(71,'Tabatinga','Tabatinga','Aeroporto Internacional de Tabatinga','SBTT','TBT','Tabatinga/AM','Infraero'),
		(72,'Tarauacá','Taraucá','Aeroporto de Tarauacá','SBTK','TRQ','Taraucá/AC','Municipal'),
		(73,'Tefé','Tefé','Aeroporto Regional de Tefé','SBTF','TFF','Tefé/AM','Infraero'),
		(74,'Teresina','Teresina','Aeroporto de Teresina','SBTE','THE','Teresina/PI','Infraero'),
		(75,'Tirios','Óbidos Tirios','Base Área de Tirios','SBTS','null','Óbidos/PA','Força Aérea Brasileira'),
		(76,'Xapuri','Xapuri','AeroportodeXapuri','SWXU','null','Xapuri/AC','Municipal');